### PR TITLE
Choco sucks ass

### PR DESCRIPTION
**Pull request by HerXayah**
Due to RAM Management beeing fine in Windows since 1909 and less Programs and such open due to it beeing a Systemservice

### CODE REVIEW

**Comment by he3als** [comment]
If you are on Windows 10 2004 and above, forcing the timer is not necessary at all as it is automatically done by the game/application you are using.

**Comment by HerXayah** [comment]
True, but not much ppl are on these Actually *sadly*

**Comment by HerXayah** [comment]
Added Scoop
removed choco
added nvcleanstall installer script

**Comment by couleurm** [comment]
I appreciate the contributions but some stuff is too personnal

* Scoop viewer lacks a lot of basic apps
* Toolbox is dead anyways AIO-CLI is gonna replace a lot of automation stuff and my **soonTM** HalfChoco/HalfScoop GUI will replace it as well
* Not that I don't trust you but I don't feel safe linking to scripts on domains you own, if there ever is a security problem I don't want to blame it on anyone else than myself

**Comment by HerXayah** [comment]
add dynamic download of nvcleanstall or host it urself then ^^
wasnt able to bc honestly. techpowerup download sucks...

**Comment by Aetopia** [comment]
> 
> 
> I appreciate the contributions but some stuff is too personnal
> 
>     * Scoop viewer lacks a lot of basic apps
> 
>     * Toolbox is dead anyways AIO-CLI is gonna replace a lot of automation stuff and my **soonTM** HalfChoco/HalfScoop GUI will replace it as well
> 
>     * Not that I don't trust you but I don't feel safe linking to scripts on domains you own, if there ever is a security problem I don't want to blame it on anyone else than myself

The issue will more be of rewriting toolbox for being scoop only.
which would a pain in the butt honestly.

**Comment by vladaad** [comment]
Ignoring scoop and focusing on NVCleanInstall:
You should be able to just send a POST request to `https://www.techpowerup.com/download/techpowerup-nvcleanstall/` with the data of `id=1905&server_id=8` (or a different server ID, I chose Germany) to get a direct download link

**Comment by vladaad** [comment]
Can be achieved with `curl.exe -L -d 'id=1905&server_id=8' https://www.techpowerup.com/download/techpowerup-nvcleanstall/ -o NVCleanInstall.exe`

**Pull request closed without merging**
