### PR TITLE
Bedrock edition resource packs

### PR DESCRIPTION
**Pull request by aShanki**
Added a couple bedrock edition pack folders along with some individual pack videos.

### CODE REVIEW

**Comment by vladaad** [comment]
Please only include the relevant commits

**Comment by aShanki** [comment]
> Please only include the relevant commits

how do i... do that...

**Comment by aShanki** [comment]
oh wait i'm dumb. let me close the pull requests i made

**Comment by vladaad** [comment]
You don't need to close, just rebase

**Pull request closed without merging**
